# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12d11b8bcabdf5cb4e859b52ae3c028d95cb4c16e1628bc7f06abe4d8079a95972684206fa20a151d0400cd7e0adec8966b71f9b572cce7ee93914ba41e822bb

test:
  secret_key_base: 985a9022de1731aa802014901baa6acf19ec1790384a298445bb002deebf7486df01f3c75e2f65721267a9ab17fc3c156a1cec8c8e6b7cfb3ff7c9c381b7a1e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
